//import { FileObject } from './files';
import { File } from '@web-std/file'

export abstract class StorageProvider {
	/**
	 * Returns the CID
	 * @param files - Files array to upload on ipfs
	 * @returns Returns the CID generated by the provider
	 */
	abstract uploadAll(files: File[]): Promise<string>;

	/**
	 * Returns the CID
	 * @param file - File to upload on ipfs
	 * @returns Returns the CID generated by the provider
	 */
	abstract upload(file: File): Promise<string>;
}
