import { FileObject } from 'files-from-path';

export abstract class StorageProvider {
	/**
	 * Returns the CID
	 * @param files - FilesObject array to upload on ipfs
	 * @returns Returns the CID generated by the provider
	 */
	abstract upload(files: FileObject[]): Promise<string>;
}
