/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export type PartyType = {
    max_edition: number;
} | {
    duration: number;
};
export type Uint128 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface InstantiateMsg {
    bs721_admin: string;
    bs721_code_id: number;
    max_per_address?: number | null;
    name: string;
    party_type: PartyType;
    payment_address: string;
    price: Coin;
    protocol_fee_bps: number;
    referral_fee_bps: number;
    seller_fee_bps: number;
    start_time: Timestamp;
    symbol: string;
    uri: string;
}
export interface Coin {
    amount: Uint128;
    denom: string;
    [k: string]: unknown;
}
export type ExecuteMsg = {
    mint: {
        amount: number;
        referral?: string | null;
    };
};
export type QueryMsg = {
    get_config: {};
} | {
    max_per_address: {
        address: string;
    };
};
export type Addr = string;
export interface Config {
    bs721_address?: Addr | null;
    creator: Addr;
    max_per_address?: number | null;
    name: string;
    next_token_id: number;
    party_type: PartyType;
    payment_address: Addr;
    price: Coin;
    protocol_fee_bps: number;
    referral_fee_bps: number;
    seller_fee_bps: number;
    start_time: Timestamp;
    symbol: string;
    uri: string;
}
export interface MaxPerAddressResponse {
    remaining?: number | null;
}
