/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./Bs721Base.client";
import * as _3 from "./LaunchpadFixed.client";
export declare namespace contracts {
    const Bs721Base: {
        Bs721BaseQueryClient: typeof _1.Bs721BaseQueryClient;
        Bs721BaseClient: typeof _1.Bs721BaseClient;
    };
    const LaunchpadFixed: {
        LaunchpadFixedQueryClient: typeof _3.LaunchpadFixedQueryClient;
        LaunchpadFixedClient: typeof _3.LaunchpadFixedClient;
    };
}
