/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./Bs721Base.client";
import * as _3 from "./Bs721Curve.client";
import * as _5 from "./Bs721Factory.client";
import * as _7 from "./Bs721Launchparty.client";
import * as _9 from "./Bs721Royalties.client";
export declare namespace contracts {
    const Bs721Base: {
        Bs721BaseQueryClient: typeof _1.Bs721BaseQueryClient;
        Bs721BaseClient: typeof _1.Bs721BaseClient;
    };
    const Bs721Curve: {
        Bs721CurveQueryClient: typeof _3.Bs721CurveQueryClient;
        Bs721CurveClient: typeof _3.Bs721CurveClient;
    };
    const Bs721Factory: {
        Bs721FactoryQueryClient: typeof _5.Bs721FactoryQueryClient;
        Bs721FactoryClient: typeof _5.Bs721FactoryClient;
    };
    const Bs721Launchparty: {
        Bs721LaunchpartyQueryClient: typeof _7.Bs721LaunchpartyQueryClient;
        Bs721LaunchpartyClient: typeof _7.Bs721LaunchpartyClient;
    };
    const Bs721Royalties: {
        Bs721RoyaltiesQueryClient: typeof _9.Bs721RoyaltiesQueryClient;
        Bs721RoyaltiesClient: typeof _9.Bs721RoyaltiesClient;
    };
}
