/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Coin, ConfigResponse } from "./LaunchpartyFixed.types";
export interface LaunchpartyFixedReadOnlyInterface {
    contractAddress: string;
    getConfig: () => Promise<ConfigResponse>;
}
export declare class LaunchpartyFixedQueryClient implements LaunchpartyFixedReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    getConfig: () => Promise<ConfigResponse>;
}
export interface LaunchpartyFixedInterface extends LaunchpartyFixedReadOnlyInterface {
    contractAddress: string;
    sender: string;
    mint: ({ amount, referral }: {
        amount: number;
        referral?: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class LaunchpartyFixedClient extends LaunchpartyFixedQueryClient implements LaunchpartyFixedInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    mint: ({ amount, referral }: {
        amount: number;
        referral?: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
