/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
export type Addr = string;
export type Uint128 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface InstantiateMsg {
    base_token_uri: string;
    collection_uri: string;
    contributors: Contributor[];
    creator: Addr;
    max_editions: number;
    name: string;
    price: Uint128;
    seller_fee_bps: number;
    start_time: Timestamp;
    symbol: string;
}
export interface Contributor {
    addr: string;
    weight: number;
}
export type ExecuteMsg = {
    mint: {};
};
export type QueryMsg = {
    get_config: {};
};
export interface ConfigResponse {
    base_token_uri: string;
    bs721_address?: Addr | null;
    creator: Addr;
    max_editions: number;
    name: string;
    next_token_id: number;
    price: Uint128;
    royalty_address?: Addr | null;
    seller_fee_bps: number;
    start_time: Timestamp;
    symbol: string;
}
