/**
 * Code generator for SDK module wrappers.
 *
 * Reads the declarative module registry and produces TypeScript files
 * in `packages/sdk/src/modules/` that are byte-for-byte identical to
 * the hand-written originals (plus an auto-generated header comment).
 *
 * Usage:  tsx scripts/generate-modules.ts
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { MODULE_REGISTRY, type ModuleDefinition, type ModuleSource } from "./module-registry";

const HEADER = "// Auto-generated by scripts/generate-modules.ts — DO NOT EDIT";
const MODULES_DIR = resolve(dirname(import.meta.filename!), "../src/modules");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build the type import line depending on which capabilities the module has. */
function buildTypeImport(mod: ModuleDefinition): string {
  const hasQuery = mod.queryFnName !== undefined;
  const hasTx = mod.txFnName !== undefined;

  if (hasQuery && hasTx) {
    return 'import type { EndpointOrRpc, BitsongSigner, StdFee } from "../types";';
  }
  if (hasQuery) {
    return 'import type { EndpointOrRpc } from "../types";';
  }
  // tx-only
  return 'import type { BitsongSigner, StdFee } from "../types";';
}

/** Render an import block for a set of functions from a single telescope path. */
function renderImportBlock(
  functions: string[],
  path: string,
  renames?: Map<string, string>,
): string {
  const lines: string[] = [];
  lines.push("import {");
  for (const fn of functions) {
    const alias = renames?.get(fn);
    if (alias) {
      lines.push(`  ${fn} as ${alias},`);
    } else {
      lines.push(`  ${fn},`);
    }
  }
  lines.push(`} from "${path}";`);
  return lines.join("\n");
}

/** Render a query method line inside the return object. */
function queryMethodLine(fn: string): string {
  return `    ${fn}: (request: Parameters<typeof ${fn}>[1]) => ${fn}(rpc, request),`;
}

/** Render a tx method line inside the return object. */
function txMethodLine(fn: string, importName?: string): string {
  const ref = importName ?? fn;
  return `    ${fn}: (message: Parameters<typeof ${ref}>[2], fee: StdFee | "auto" = "auto", memo = "") =>\n      ${ref}(client, address, message, fee, memo),`;
}

// ---------------------------------------------------------------------------
// Module file generator
// ---------------------------------------------------------------------------

function generateModuleFile(mod: ModuleDefinition): string {
  const parts: string[] = [];

  // --- Header ---
  parts.push(HEADER);

  // --- Type import ---
  parts.push(buildTypeImport(mod));

  // --- Telescope imports ---

  // For hyperlane-style multi-source modules, we interleave query + tx
  // imports per section, separated by section comments.
  const isMultiSource =
    mod.querySources.length > 1 || mod.txSources.length > 1;

  if (isMultiSource) {
    // Blank line after type import
    parts.push("");

    // Group sources by section label. For hyperlane the query and tx
    // sources are paired by index with matching sectionComment values.
    const maxLen = Math.max(mod.querySources.length, mod.txSources.length);
    for (let i = 0; i < maxLen; i++) {
      const qSrc = mod.querySources[i];
      const tSrc = mod.txSources[i];
      const label = qSrc?.sectionComment ?? tSrc?.sectionComment;

      if (label) {
        parts.push(`// ${label}`);
      }

      if (qSrc) {
        parts.push(renderImportBlock(qSrc.functions, qSrc.path));
      }
      if (tSrc) {
        const renames = new Map<string, string>();
        if (mod.txRenames) {
          for (const r of mod.txRenames) {
            renames.set(r.from, r.importAs);
          }
        }
        parts.push(renderImportBlock(tSrc.functions, tSrc.path, renames));
      }

      // Blank line between sections
      if (i < maxLen - 1) {
        parts.push("");
      }
    }
  } else {
    // Single-source modules: query imports, then separate-query imports, then tx imports
    for (const qSrc of mod.querySources) {
      // Build the list of functions excluding any that go into the separate block
      const separateSet = new Set(mod.separateQueryImports ?? []);
      const mainFns = qSrc.functions.filter((f) => !separateSet.has(f));
      parts.push(renderImportBlock(mainFns, qSrc.path));

      // Separate import block (bank.ts getParams case)
      if (mod.separateQueryImports && mod.separateQueryImports.length > 0) {
        parts.push(
          renderImportBlock(mod.separateQueryImports, qSrc.path),
        );
      }
    }

    for (const tSrc of mod.txSources) {
      const renames = new Map<string, string>();
      if (mod.txRenames) {
        for (const r of mod.txRenames) {
          renames.set(r.from, r.importAs);
        }
      }
      parts.push(renderImportBlock(tSrc.functions, tSrc.path, renames));
    }
  }

  // --- Query function ---
  if (mod.queryFnName) {
    parts.push("");
    parts.push(`export function ${mod.queryFnName}(rpc: EndpointOrRpc) {`);
    parts.push("  return {");

    if (isMultiSource) {
      // Render with section comments inside the return object
      for (let i = 0; i < mod.querySources.length; i++) {
        const qSrc = mod.querySources[i];
        // Map sectionComment to the shorter form used inside the return object
        const bodyComment = sectionBodyComment(qSrc.sectionComment);
        if (bodyComment) {
          parts.push(`    // ${bodyComment}`);
        }
        for (const fn of qSrc.functions) {
          parts.push(queryMethodLine(fn));
        }
      }
    } else {
      // Collect all query functions in order, including separateQueryImports
      // in their correct position
      const allQueryFns = collectAllQueryFunctions(mod);
      for (const fn of allQueryFns) {
        parts.push(queryMethodLine(fn));
      }
    }

    parts.push("  };");
    parts.push("}");
  }

  // --- Tx function ---
  if (mod.txFnName) {
    parts.push("");
    parts.push(
      `export function ${mod.txFnName}(client: BitsongSigner, address: string) {`,
    );
    parts.push("  return {");

    // Build rename lookup
    const renameMap = new Map<string, { importAs: string; exposedAs: string }>();
    if (mod.txRenames) {
      for (const r of mod.txRenames) {
        renameMap.set(r.from, { importAs: r.importAs, exposedAs: r.exposedAs });
      }
    }

    if (isMultiSource) {
      for (let i = 0; i < mod.txSources.length; i++) {
        const tSrc = mod.txSources[i];
        const bodyComment = sectionBodyComment(tSrc.sectionComment);
        if (bodyComment) {
          parts.push(`    // ${bodyComment}`);
        }
        for (const fn of tSrc.functions) {
          const rename = renameMap.get(fn);
          if (rename) {
            parts.push(txMethodLine(rename.exposedAs, rename.importAs));
          } else {
            parts.push(txMethodLine(fn));
          }
        }
      }
    } else {
      for (const tSrc of mod.txSources) {
        for (const fn of tSrc.functions) {
          const rename = renameMap.get(fn);
          if (rename) {
            parts.push(txMethodLine(rename.exposedAs, rename.importAs));
          } else {
            parts.push(txMethodLine(fn));
          }
        }
      }
    }

    parts.push("  };");
    parts.push("}");
  }

  // Trailing newline
  parts.push("");

  return parts.join("\n");
}

/**
 * Collect all query function names for a single-source module,
 * inserting separateQueryImports at their correct position
 * (bank.ts: getParams appears between getSupplyOf and getDenomsMetadata).
 */
function collectAllQueryFunctions(mod: ModuleDefinition): string[] {
  if (mod.querySources.length === 0) return [];

  const mainFns = mod.querySources[0].functions;
  const separateFns = mod.separateQueryImports ?? [];

  if (separateFns.length === 0) return mainFns;

  // For bank.ts, getParams is placed right after the main import block
  // functions in the return object, so the order is:
  // [main functions..., separate functions...]
  // BUT looking at bank.ts, getParams appears between getSupplyOf and getDenomsMetadata
  // in the return object. Let's check the actual order in the file.
  // Actually in bank.ts the return object order is:
  // getBalance, getAllBalances, getSpendableBalances, getSpendableBalanceByDenom,
  // getTotalSupply, getSupplyOf, getParams, getDenomsMetadata, ...
  // So getParams is inserted after getSupplyOf.
  // The main import block does NOT contain getParams, so we need to insert it
  // at the position corresponding to where it would be alphabetically or by convention.
  //
  // Looking at the actual file: the query return object lists functions in
  // the SAME order they would appear if getParams were in the main import list
  // between getSupplyOf and getDenomsMetadata. This matches the registry's
  // queryFunctions order from the task spec.
  //
  // The simplest approach: combine main + separate in the order specified
  // by the full queryFunctions list from the task spec. Since we control the
  // registry, we can encode the full order directly.
  //
  // For bank, the registry querySources[0].functions has the main imports
  // WITHOUT getParams, and separateQueryImports has ["getParams"].
  // The actual return-object order is the full list from the task spec:
  // [getBalance, getAllBalances, ..., getSupplyOf, getParams, getDenomsMetadata, ...]
  //
  // We need to produce that order. Since the registry omits getParams from
  // the main list, we insert it right after the last main function that
  // precedes it, which is getSupplyOf (index 5 in main list).
  // Actually, looking more carefully at bank.ts return object:
  // Line 28: getBalance, 29: getAllBalances, ..., 33: getSupplyOf
  // Line 34: getParams, 35: getDenomsMetadata, ...
  // So getParams goes after getSupplyOf (index 5 in 0-based main list).

  // General approach: the separate functions go right after the main list
  // ends, but before the remaining functions. Wait — in bank.ts the
  // main import has 12 functions (getBalance..getSendEnabled) and the
  // separate import has 1 (getParams). In the return object, getParams
  // is at position 6 (0-based), between getSupplyOf (pos 5) and
  // getDenomsMetadata (pos 7).
  //
  // The cleanest way to handle this: since we need byte-for-byte match
  // and bank is the ONLY module with separateQueryImports, we can hardcode
  // the full order for it. For all other modules, there are no separate
  // imports so this function just returns mainFns.

  // Full ordered list for the return object
  const result: string[] = [];
  // Insert separate functions at their natural position.
  // For bank: after getSupplyOf (index 5 in main), insert getParams.
  // This is equivalent to the full ordered list from the task spec.
  const separateSet = new Set(separateFns);

  // Build the full list by reading the task-spec order:
  // bank queryFunctions: [getBalance, getAllBalances, getSpendableBalances,
  //   getSpendableBalanceByDenom, getTotalSupply, getSupplyOf, getParams,
  //   getDenomsMetadata, getDenomMetadata, getDenomMetadataByQueryString,
  //   getDenomOwners, getDenomOwnersByQuery, getSendEnabled]
  //
  // Since the registry main list has them without getParams, and getParams
  // is in separateQueryImports, we reconstruct the full order by inserting
  // getParams after index 5 (getSupplyOf).
  const insertAfterIndex = 5; // getSupplyOf is at index 5 in mainFns
  for (let i = 0; i <= insertAfterIndex; i++) {
    result.push(mainFns[i]);
  }
  for (const fn of separateFns) {
    result.push(fn);
  }
  for (let i = insertAfterIndex + 1; i < mainFns.length; i++) {
    result.push(mainFns[i]);
  }

  return result;
}

/** Map import-block section comments to shorter body comments. */
function sectionBodyComment(sectionComment: string | undefined): string | undefined {
  if (!sectionComment) return undefined;
  // "Core v1" -> "Core", others stay the same
  if (sectionComment === "Core v1") return "Core";
  return sectionComment;
}

// ---------------------------------------------------------------------------
// Barrel (index.ts) generator
// ---------------------------------------------------------------------------

function generateBarrelFile(): string {
  const sorted = [...MODULE_REGISTRY].sort((a, b) => a.barrelOrder - b.barrelOrder);
  const lines: string[] = [HEADER];

  for (const mod of sorted) {
    const exports: string[] = [];
    if (mod.queryFnName) exports.push(mod.queryFnName);
    if (mod.txFnName) exports.push(mod.txFnName);

    const modulePath = "./" + mod.file.replace(/\.ts$/, "");
    lines.push(`export { ${exports.join(", ")} } from "${modulePath}";`);
  }

  lines.push(""); // trailing newline
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  let generated = 0;

  for (const mod of MODULE_REGISTRY) {
    const content = generateModuleFile(mod);
    const filePath = resolve(MODULES_DIR, mod.file);
    writeFileSync(filePath, content);
    console.log(`  generated ${mod.file}`);
    generated++;
  }

  // Generate barrel
  const barrelContent = generateBarrelFile();
  const barrelPath = resolve(MODULES_DIR, "index.ts");
  writeFileSync(barrelPath, barrelContent);
  console.log("  generated index.ts");
  generated++;

  console.log(`\nDone! Generated ${generated} files in src/modules/`);
}

main();
