/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.21.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Bs721Base.types";
import * as _1 from "./Bs721Base.client";
import * as _2 from "./LaunchpartyFixed.types";
import * as _3 from "./LaunchpartyFixed.client";
export namespace contracts {
  export const Bs721Base = { ..._0,
    ..._1
  };
  export const LaunchpartyFixed = { ..._2,
    ..._3
  };
}