import { validateUploadPayload } from '../utils';
import { StorageProvider } from '@bitsongjs/storage';
import { NFTUploadResponse } from '../types';

export class NFTUploader {
	constructor(private provider: StorageProvider) {}

	/**
	 * Returns the CID
	 * @param images - File array to upload on ipfs (It's related to Web File api)
	 * @param rawMetadata - File array to upload on ipfs (It's related to Web File api)
	 * @returns Returns the CID generated by the provider
	 */
	async upload(images: File[], rawMetadata: File[]): Promise<NFTUploadResponse> {
		validateUploadPayload(images, rawMetadata);

		const imagesCID = await this.provider.upload(images);

		const metadata: File[] = [];

		for (const [index, data] of rawMetadata.entries()) {
			const txtData = await data.text();
			const jsonData = JSON.parse(txtData);

			jsonData.image = `ipfs://${imagesCID}${images[index].name}`;

			const file = new File([JSON.stringify(jsonData)], data.name, {
				type: 'application/json',
			});

			metadata.push(file);
		}

		console.log(metadata);

		const metadataCID = await this.provider.upload(metadata);

		const uri = `ipfs://${imagesCID}`;

		return {
			uri,
		};
	}
}
